---
- name: postgres_exporter | create user
  become: true
  user:
    name: "{{ postgres_exporter_user }}"
    comment: "postgres_exporter user"
    createhome: false
    move_home: false
    shell: /bin/false
    state: present
    system: true
  when: postgres_exporter_user is defined and postgres_exporter_user != 'postgres'

- name: postgres_exporter | create exporter directories
  become: true
  file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ prometheus_exporters_dir }}"
    - "{{ postgres_exporter_query_dir }}"

- name: postgres_exporter | create logs directory
  become: true
  file:
    path: "{{ postgres_exporter_log_path }}"
    owner: "{{ postgres_exporter_user }}"
    mode: '0750'
    state: directory
  when: postgres_exporter_log_path is defined

- name: postgres_exporter | download exporter
  become: true
  get_url:
    url: "{{ postgres_exporter_url }}"
    checksum: sha256:{{ postgres_exporter_checksum }}
    dest: "/tmp/postgres_exporter\
      -{{ postgres_exporter_version }}.linux-amd64.tar.gz"

- name: postgres_exporter | unarchive postgres_exporter
  become: true
  unarchive:
    src: "/tmp/postgres_exporter\
      -{{ postgres_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_exporters_dir }}"
    group: root
    owner: root
    remote_src: true

- name: postgres_exporter | install postgres_exporter to {{ postgres_exporter_dist_dir }}
  become: true
  file:
    src: "{{ prometheus_exporters_dir }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64/postgres_exporter"
    path: "{{ prometheus_exporters_dir }}/postgres_exporter"
    owner: root
    group: root
    force: true
    state: link
    # remote_src: true
    # mode: '0755'
  notify: restart postgres_exporter

- name: postgres_exporter | create config file
  become: true
  become_user: root
  template:
    src: "postgres_exporter.default.conf.j2"
    dest: "{{ postgres_exporter_config_file }}"
    owner: root
    group: root
    mode: "0640"
  notify: restart postgres_exporter

- name: postgres_exporter | copy queries file
  become: true
  become_user: root
  copy:
    src: "{{ postgres_exporter_queries }}"
    dest: "{{ postgres_exporter_query_dir }}/queries.yml"
    owner: "{{ postgres_exporter_user }}"
    mode: "0640"
  notify: restart postgres_exporter

- name: postgres_exporter | systemd configuration
  include: service-systemd.yml

- name: postgres_exporter | start postgres_exporter
  become: true
  become_user: root
  service:
    daemon_reload: true
    enabled: true
    name: postgres_exporter
    state: started
