---
- name: postgres_exporter | create systemd service
  become: true
  ansible.builtin.template:
    src: "postgres_exporter.systemd.j2"
    dest: "/etc/systemd/system/postgres_exporter.service"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - restart postgres_exporter
